// questions.js
const QUESTION_BANK = [
  // =========================
  // HTML (1 - 34)
  // =========================
  {
    id: 1,
    topic: "HTML",
    question: "What is a webpage?",
    options: [
      "A single document displayed in a browser",
      "A group of servers connected to the internet",
      "A programming language for styling",
      "A database table for users",
    ],
    answer: 0,
    explanation: "A webpage is one page/document viewed in a browser.",
  },
  {
    id: 2,
    topic: "HTML",
    question: "What is a website?",
    options: [
      "A collection of related webpages under one domain",
      "A single HTML tag",
      "A web browser extension",
      "A server operating system",
    ],
    answer: 0,
    explanation: "A website is multiple pages linked together.",
  },
  {
    id: 3,
    topic: "HTML",
    question: "Which tool is used to view webpages?",
    options: ["Web browser", "Text editor", "Compiler", "Database"],
    answer: 0,
    explanation: "Browsers render HTML/CSS/JS into visible pages.",
  },
  {
    id: 4,
    topic: "HTML",
    question: "Which is a text editor commonly used for web development?",
    options: ["VS Code", "Chrome", "MySQL", "Apache"],
    answer: 0,
    explanation: "VS Code is a text editor for writing code.",
  },
  {
    id: 5,
    topic: "HTML",
    question: "What does URL stand for?",
    options: [
      "Uniform Resource Locator",
      "Universal Render Language",
      "User Reference Link",
      "Unified Routing Level",
    ],
    answer: 0,
    explanation: "URL = Uniform Resource Locator.",
  },
  {
    id: 6,
    topic: "HTML",
    question: "What is a hyperlink used for?",
    options: [
      "To connect one page/resource to another",
      "To change background color",
      "To store data in the browser",
      "To create a database relationship",
    ],
    answer: 0,
    explanation: "Links navigate to another page, section, or resource.",
  },
  {
    id: 7,
    topic: "HTML",
    question: "Which file extension is correct for an HTML file?",
    options: [".html", ".css", ".js", ".php"],
    answer: 0,
    explanation: "HTML files typically end with .html",
  },
  {
    id: 8,
    topic: "HTML",
    question: "Which tag defines the main structure of an HTML document?",
    options: ["<!DOCTYPE html>", "<meta>", "<link>", "<script>"],
    answer: 0,
    explanation: "DOCTYPE tells the browser to use HTML5 standards mode.",
  },
  {
    id: 9,
    topic: "HTML",
    question: "Which tag contains metadata like charset and title links?",
    options: ["<head>", "<body>", "<footer>", "<section>"],
    answer: 0,
    explanation: "<head> contains metadata and resource links.",
  },
  {
    id: 10,
    topic: "HTML",
    question: "Which tag displays visible content on the page?",
    options: ["<body>", "<head>", "<title>", "<meta>"],
    answer: 0,
    explanation: "Visible elements are inside <body>.",
  },
  {
    id: 11,
    topic: "HTML",
    question: "Which is a correct heading tag order (largest to smallest)?",
    options: ["<h1> to <h6>", "<h6> to <h1>", "<p> to <h1>", "<title> to <h6>"],
    answer: 0,
    explanation: "Heading levels go from h1 (largest) to h6 (smallest).",
  },
  {
    id: 12,
    topic: "HTML",
    question: "Which tag is used for a paragraph?",
    options: ["<p>", "<h1>", "<div>", "<span>"],
    answer: 0,
    explanation: "<p> is for paragraphs.",
  },
  {
    id: 13,
    topic: "HTML",
    question: "Which tag creates a line break?",
    options: ["<br>", "<hr>", "<p>", "<li>"],
    answer: 0,
    explanation: "<br> inserts a line break.",
  },
  {
    id: 14,
    topic: "HTML",
    question: "Which tag creates a horizontal line separator?",
    options: ["<hr>", "<br>", "<span>", "<div>"],
    answer: 0,
    explanation: "<hr> is a thematic break line.",
  },
  {
    id: 15,
    topic: "HTML",
    question: "Which tag is used for an unordered list?",
    options: ["<ul>", "<ol>", "<li>", "<list>"],
    answer: 0,
    explanation: "<ul> is unordered list; <li> is list item.",
  },
  {
    id: 16,
    topic: "HTML",
    question: "Which tag is used for an ordered list?",
    options: ["<ol>", "<ul>", "<li>", "<order>"],
    answer: 0,
    explanation: "<ol> creates a numbered list.",
  },
  {
    id: 17,
    topic: "HTML",
    question: "Which tag defines a list item?",
    options: ["<li>", "<ul>", "<ol>", "<item>"],
    answer: 0,
    explanation: "<li> is used inside ul/ol.",
  },
  {
    id: 18,
    topic: "HTML",
    question: "Which tag is used to display an image?",
    options: ["<img>", "<image>", "<picture>", "<src>"],
    answer: 0,
    explanation: "<img> displays an image using src attribute.",
  },
  {
    id: 19,
    topic: "HTML",
    question: "Which attribute is required to specify the image file location?",
    options: ["src", "alt", "href", "type"],
    answer: 0,
    explanation: "src points to the image resource.",
  },
  {
    id: 20,
    topic: "HTML",
    question: "Which attribute helps SEO/accessibility for images?",
    options: ["alt", "src", "width", "class"],
    answer: 0,
    explanation: "alt provides text alternative for screen readers and SEO.",
  },
  {
    id: 21,
    topic: "HTML",
    question: "Which tag creates a link to another page?",
    options: ["<a>", "<link>", "<href>", "<nav>"],
    answer: 0,
    explanation: "<a href='...'> is hyperlink.",
  },
  {
    id: 22,
    topic: "HTML",
    question: "Which attribute defines the destination of an <a> tag?",
    options: ["href", "src", "target", "rel"],
    answer: 0,
    explanation: "href is the URL destination.",
  },
  {
    id: 23,
    topic: "HTML",
    question: "Which value opens a link in a new tab?",
    options: ['target="_blank"', 'target="_self"', 'rel="nofollow"', 'href="_blank"'],
    answer: 0,
    explanation: "target='_blank' opens a new tab/window.",
  },
  {
    id: 24,
    topic: "HTML",
    question: "Which tag is used to group content as a block container?",
    options: ["<div>", "<span>", "<em>", "<strong>"],
    answer: 0,
    explanation: "<div> is a block-level grouping container.",
  },
  {
    id: 25,
    topic: "HTML",
    question: "Which tag is used to group inline text?",
    options: ["<span>", "<div>", "<section>", "<article>"],
    answer: 0,
    explanation: "<span> is an inline container.",
  },
  {
    id: 26,
    topic: "HTML",
    question: "Which semantic tag is best for site navigation?",
    options: ["<nav>", "<div>", "<span>", "<table>"],
    answer: 0,
    explanation: "<nav> indicates navigation links section.",
  },
  {
    id: 27,
    topic: "HTML",
    question: "Which semantic tag is best for main content of the page?",
    options: ["<main>", "<aside>", "<footer>", "<header>"],
    answer: 0,
    explanation: "<main> holds the primary content.",
  },
  {
    id: 28,
    topic: "HTML",
    question: "Which tag is used for a table row?",
    options: ["<tr>", "<td>", "<th>", "<table>"],
    answer: 0,
    explanation: "<tr> is a table row.",
  },
  {
    id: 29,
    topic: "HTML",
    question: "Which tag is used for table header cell?",
    options: ["<th>", "<td>", "<tr>", "<thead>"],
    answer: 0,
    explanation: "<th> is a header cell (bold by default).",
  },
  {
    id: 30,
    topic: "HTML",
    question: "Which tag is used for table data cell?",
    options: ["<td>", "<th>", "<tr>", "<tbody>"],
    answer: 0,
    explanation: "<td> holds regular table data.",
  },
  {
    id: 31,
    topic: "HTML",
    question: "Which element is used to collect user input text?",
    options: ["<input>", "<form>", "<label>", "<fieldset>"],
    answer: 0,
    explanation: "<input> creates an input field.",
  },
  {
    id: 32,
    topic: "HTML",
    question: "Which attribute is important for sending form data (input key name)?",
    options: ["name", "id", "class", "style"],
    answer: 0,
    explanation: "name is the key used in submitted form data.",
  },
  {
    id: 33,
    topic: "HTML",
    question: "Which tag is used to write a comment in HTML?",
    options: ["<!-- comment -->", "// comment", "/* comment */", "# comment"],
    answer: 0,
    explanation: "HTML comments use <!-- -->.",
  },
  {
    id: 34,
    topic: "HTML",
    question: "Which tag is best for SEO page title shown in the browser tab?",
    options: ["<title>", "<h1>", "<meta>", "<header>"],
    answer: 0,
    explanation: "<title> sets the page title in the tab/search results.",
  },

  // =========================
  // CSS (35 - 67)
  // =========================
  {
    id: 35,
    topic: "CSS",
    question: "What is CSS mainly used for?",
    options: [
      "Styling and layout of webpages",
      "Storing data in database",
      "Creating server routes",
      "Compiling JavaScript",
    ],
    answer: 0,
    explanation: "CSS controls design and layout.",
  },
  {
    id: 36,
    topic: "CSS",
    question: "Which is a correct CSS syntax?",
    options: [
      "selector { property: value; }",
      "selector ( property = value )",
      "{ selector: property=value }",
      "property: value -> selector",
    ],
    answer: 0,
    explanation: "CSS uses selector { property: value; }",
  },
  {
    id: 37,
    topic: "CSS",
    question: "In CSS, what is a selector?",
    options: [
      "The part that chooses which HTML elements to style",
      "The part that sets the property value",
      "A JavaScript function name",
      "A database query",
    ],
    answer: 0,
    explanation: "Selector targets elements like p, .class, #id.",
  },
  {
    id: 38,
    topic: "CSS",
    question: "In CSS, what is a declaration?",
    options: [
      "property: value;",
      "A HTML comment",
      "A file extension",
      "A URL address",
    ],
    answer: 0,
    explanation: "Declarations are property-value pairs.",
  },
  {
    id: 39,
    topic: "CSS",
    question: "Which is inline CSS?",
    options: [
      '<p style="color:red;">Hi</p>',
      "<style>p{color:red;}</style>",
      '<link rel="stylesheet" href="style.css">',
      '@import "style.css";',
    ],
    answer: 0,
    explanation: "Inline CSS is in the style attribute.",
  },
  {
    id: 40,
    topic: "CSS",
    question: "Which is internal CSS?",
    options: [
      "<style>p{color:red;}</style>",
      '<p style="color:red;">Hi</p>',
      '<link rel="stylesheet" href="style.css">',
      "p:color=red",
    ],
    answer: 0,
    explanation: "Internal CSS is inside <style> in the HTML file.",
  },
  {
    id: 41,
    topic: "CSS",
    question: "Which is external CSS?",
    options: [
      '<link rel="stylesheet" href="style.css">',
      '<p style="color:red;">Hi</p>',
      "<style>p{color:red;}</style>",
      "<script src='style.css'></script>",
    ],
    answer: 0,
    explanation: "External CSS uses <link> to load a .css file.",
  },
  {
    id: 42,
    topic: "CSS",
    question: "Which CSS property changes text color?",
    options: ["color", "background-color", "font-style", "display"],
    answer: 0,
    explanation: "color controls the text color.",
  },
  {
    id: 43,
    topic: "CSS",
    question: "Which property changes the background color?",
    options: ["background-color", "color", "opacity", "border-color"],
    answer: 0,
    explanation: "background-color sets background.",
  },
  {
    id: 44,
    topic: "CSS",
    question: "Which property controls transparency?",
    options: ["opacity", "visibility", "display", "z-index"],
    answer: 0,
    explanation: "opacity ranges 0 to 1.",
  },
  {
    id: 45,
    topic: "CSS",
    question: "Which property sets a background image?",
    options: ["background-image", "image-src", "bg-src", "background-photo"],
    answer: 0,
    explanation: "background-image: url(...);",
  },
  {
    id: 46,
    topic: "CSS",
    question: "Which display value hides an element but keeps its space?",
    options: ["visibility: hidden", "display: none", "opacity: 0", "position: fixed"],
    answer: 0,
    explanation: "visibility:hidden keeps layout space; display:none removes it.",
  },
  {
    id: 47,
    topic: "CSS",
    question: "Which display value removes an element from layout completely?",
    options: ["display: none", "visibility: hidden", "opacity: 0", "position: relative"],
    answer: 0,
    explanation: "display:none removes from layout flow.",
  },
  {
    id: 48,
    topic: "CSS",
    question: "Which position type places element relative to its normal position?",
    options: ["relative", "absolute", "fixed", "sticky"],
    answer: 0,
    explanation: "position:relative offsets from normal position.",
  },
  {
    id: 49,
    topic: "CSS",
    question: "Which position type places element relative to nearest positioned ancestor?",
    options: ["absolute", "relative", "fixed", "static"],
    answer: 0,
    explanation: "absolute uses nearest ancestor with position set (not static).",
  },
  {
    id: 50,
    topic: "CSS",
    question: "Which position type stays in the same place on screen during scroll?",
    options: ["fixed", "absolute", "relative", "static"],
    answer: 0,
    explanation: "fixed attaches to viewport.",
  },
  {
    id: 51,
    topic: "CSS",
    question: "Which position type behaves like relative until it reaches a scroll point?",
    options: ["sticky", "fixed", "absolute", "static"],
    answer: 0,
    explanation: "sticky sticks after crossing a threshold like top: 0.",
  },
  {
    id: 52,
    topic: "CSS",
    question: "Which property sets element width?",
    options: ["width", "size", "length", "box-width"],
    answer: 0,
    explanation: "width sets the element width.",
  },
  {
    id: 53,
    topic: "CSS",
    question: "Which property sets element height?",
    options: ["height", "size", "length", "box-height"],
    answer: 0,
    explanation: "height sets the element height.",
  },
  {
    id: 54,
    topic: "CSS",
    question: "Which property creates space inside the border?",
    options: ["padding", "margin", "gap", "outline"],
    answer: 0,
    explanation: "Padding is inside, margin is outside.",
  },
  {
    id: 55,
    topic: "CSS",
    question: "Which property creates space outside the border?",
    options: ["margin", "padding", "gap", "outline"],
    answer: 0,
    explanation: "Margin is outside the element border.",
  },
  {
    id: 56,
    topic: "CSS",
    question: "Which property rounds the corners of an element?",
    options: ["border-radius", "border-style", "corner-radius", "radius"],
    answer: 0,
    explanation: "border-radius rounds corners.",
  },
  {
    id: 57,
    topic: "CSS",
    question: "Which property sets the border thickness/style/color?",
    options: ["border", "outline", "stroke", "edge"],
    answer: 0,
    explanation: "border: 1px solid #000; etc.",
  },
  {
    id: 58,
    topic: "CSS",
    question: "Which value centers a block element horizontally (common case)?",
    options: ["margin: 0 auto", "padding: auto", "display: center", "position: center"],
    answer: 0,
    explanation: "margin-left/right auto centers with width set.",
  },
  {
    id: 59,
    topic: "CSS",
    question: "Which property changes font size?",
    options: ["font-size", "text-size", "size", "font-weight"],
    answer: 0,
    explanation: "font-size controls text size.",
  },
  {
    id: 60,
    topic: "CSS",
    question: "Which property changes font weight (boldness)?",
    options: ["font-weight", "font-style", "font-size", "text-decoration"],
    answer: 0,
    explanation: "font-weight: 700; etc.",
  },
  {
    id: 61,
    topic: "CSS",
    question: "Which property aligns text horizontally?",
    options: ["text-align", "align-items", "justify-content", "vertical-align"],
    answer: 0,
    explanation: "text-align affects inline content inside an element.",
  },
  {
    id: 62,
    topic: "CSS",
    question: "Which CSS feature is used for responsive design?",
    options: ["media queries", "variables", "comments", "tags"],
    answer: 0,
    explanation: "@media rules change styles by screen conditions.",
  },
  {
    id: 63,
    topic: "CSS",
    question: "Which media query is best for maximum width 600px?",
    options: [
      "@media (max-width: 600px) { ... }",
      "@media (min-width: 600px) { ... }",
      "@media width <= 600 { ... }",
      "@media screen:600 { ... }",
    ],
    answer: 0,
    explanation: "max-width targets smaller screens up to 600px.",
  },
  {
    id: 64,
    topic: "CSS",
    question: "Which media orientation targets portrait mode?",
    options: [
      "@media (orientation: portrait) { ... }",
      "@media (portrait: true) { ... }",
      "@media (rotate: 0) { ... }",
      "@media (direction: portrait) { ... }",
    ],
    answer: 0,
    explanation: "orientation: portrait is correct syntax.",
  },
  {
    id: 65,
    topic: "CSS",
    question: "Which CSS type imports another CSS file inside a CSS file?",
    options: ["@import", "<link>", "<script>", "require()"],
    answer: 0,
    explanation: "@import url('file.css');",
  },
  {
    id: 66,
    topic: "CSS",
    question: "Which selector targets an element with id='main'?",
    options: ["#main", ".main", "main", "*main"],
    answer: 0,
    explanation: "# targets id.",
  },
  {
    id: 67,
    topic: "CSS",
    question: "Which selector targets elements with class='box'?",
    options: [".box", "#box", "box", "@box"],
    answer: 0,
    explanation: ". targets class.",
  },

  // =========================
  // JavaScript (68 - 100)
  // =========================
  {
    id: 68,
    topic: "JavaScript",
    question: "What is JavaScript mainly used for on a webpage?",
    options: [
      "Adding interaction and logic",
      "Creating table rows",
      "Writing server database schema",
      "Replacing CSS completely",
    ],
    answer: 0,
    explanation: "JS adds behavior (clicks, validation, DOM updates).",
  },
  {
    id: 69,
    topic: "JavaScript",
    question: "Which tag is used to include JavaScript in HTML?",
    options: ["<script>", "<style>", "<link>", "<meta>"],
    answer: 0,
    explanation: "<script> is for JavaScript.",
  },
  {
    id: 70,
    topic: "JavaScript",
    question: "What is the recommended place to load a script for beginners?",
    options: [
      "Before the closing </body> tag",
      "Inside <title>",
      "Inside <meta>",
      "Before <!DOCTYPE html>",
    ],
    answer: 0,
    explanation: "So HTML elements exist before JS runs.",
  },
  {
    id: 71,
    topic: "JavaScript",
    question: "Which keyword creates a variable that can be reassigned?",
    options: ["let", "const", "fixed", "static"],
    answer: 0,
    explanation: "let can be reassigned; const cannot.",
  },
  {
    id: 72,
    topic: "JavaScript",
    question: "Which keyword creates a variable that should not be reassigned?",
    options: ["const", "let", "var", "change"],
    answer: 0,
    explanation: "const prevents reassignment of the variable reference.",
  },
  {
    id: 73,
    topic: "JavaScript",
    question: "Which is a correct JavaScript comment (single line)?",
    options: ["// comment", "<!-- comment -->", "/*/ comment", "# comment"],
    answer: 0,
    explanation: "// starts a single-line comment in JS.",
  },
  {
    id: 74,
    topic: "JavaScript",
    question: "Which is NOT a primitive type in JavaScript?",
    options: ["object", "string", "number", "boolean"],
    answer: 0,
    explanation: "object is reference type; others listed are primitive.",
  },
  {
    id: 75,
    topic: "JavaScript",
    question: "Which function converts a string to a number (common)?",
    options: ["Number()", "String()", "Bool()", "Int()"],
    answer: 0,
    explanation: "Number('20') -> 20.",
  },
  {
    id: 76,
    topic: "JavaScript",
    question: "What is the result of '2' + 2 in JavaScript?",
    options: ["'22'", "4", "'4'", "NaN"],
    answer: 0,
    explanation: "String + number becomes string concatenation.",
  },
  {
    id: 77,
    topic: "JavaScript",
    question: "Which operator checks strict equality (value and type)?",
    options: ["===", "==", "=", "!=="],
    answer: 0,
    explanation: "=== compares value and type.",
  },
  {
    id: 78,
    topic: "JavaScript",
    question: "Which operator means 'not equal (strict)'?",
    options: ["!==", "!=", "===", "="],
    answer: 0,
    explanation: "!== checks strict not equal (type+value).",
  },
  {
    id: 79,
    topic: "JavaScript",
    question: "Which operator is used for logical AND?",
    options: ["&&", "||", "!", "&"],
    answer: 0,
    explanation: "&& requires both conditions to be true.",
  },
  {
    id: 80,
    topic: "JavaScript",
    question: "Which operator is used for logical OR?",
    options: ["||", "&&", "!", "|"],
    answer: 0,
    explanation: "|| true if at least one condition is true.",
  },
  {
    id: 81,
    topic: "JavaScript",
    question: "Which is a correct template literal syntax?",
    options: ["`Hello ${name}`", "'Hello ${name}'", '"Hello ${name}"', "`Hello (name)`"],
    answer: 0,
    explanation: "Template literals use backticks and ${}.",
  },
  {
    id: 82,
    topic: "JavaScript",
    question: "Which method removes whitespace from both ends of a string?",
    options: ["trim()", "slice()", "split()", "join()"],
    answer: 0,
    explanation: "trim() removes leading/trailing spaces.",
  },
  {
    id: 83,
    topic: "JavaScript",
    question: "Which statement is used for multiple conditions (if/else)?",
    options: ["if ... else if ... else", "for ... of", "try ... catch", "switch ... case only"],
    answer: 0,
    explanation: "if/else if/else handles multiple condition branches.",
  },
  {
    id: 84,
    topic: "JavaScript",
    question: "Which statement is best when matching fixed values (menu/options)?",
    options: ["switch", "while", "try", "import"],
    answer: 0,
    explanation: "switch is convenient for fixed cases.",
  },
  {
    id: 85,
    topic: "JavaScript",
    question: "Which loop is commonly used when you know the count?",
    options: ["for", "while", "do...while", "try...catch"],
    answer: 0,
    explanation: "for loop uses init/condition/update.",
  },
  {
    id: 86,
    topic: "JavaScript",
    question: "Which loop is best for iterating values in an array (modern)?",
    options: ["for...of", "for...in", "switch", "if...else"],
    answer: 0,
    explanation: "for...of gives values of iterable (array).",
  },
  {
    id: 87,
    topic: "JavaScript",
    question: "Which loop iterates object keys (or array indexes)?",
    options: ["for...in", "for...of", "for (;;){}", "switch"],
    answer: 0,
    explanation: "for...in iterates enumerable keys.",
  },
  {
    id: 88,
    topic: "JavaScript",
    question: "Which keyword defines a function (classic syntax)?",
    options: ["function", "func", "def", "lambda"],
    answer: 0,
    explanation: "function keyword defines a function in JS.",
  },
  {
    id: 89,
    topic: "JavaScript",
    question: "Which is a correct arrow function?",
    options: ["const add = (a,b) => a + b;", "const add(a,b) -> a+b;", "arrow add = a+b;", "function => add()"],
    answer: 0,
    explanation: "Arrow functions use =>.",
  },
  {
    id: 90,
    topic: "JavaScript",
    question: "What does 'return' do in a function?",
    options: [
      "Sends a value back and stops the function",
      "Repeats the function",
      "Prints to the screen",
      "Declares a new variable",
    ],
    answer: 0,
    explanation: "return ends function and provides output value.",
  },
  {
    id: 91,
    topic: "JavaScript",
    question: "Which creates an object literal?",
    options: ["{ name: 'A' }", "['name','A']", "(name='A')", "<object>A</object>"],
    answer: 0,
    explanation: "Object literal uses { key: value }.",
  },
  {
    id: 92,
    topic: "JavaScript",
    question: "Which creates an array?",
    options: ["[1,2,3]", "{1,2,3}", "(1,2,3)", "<array>1</array>"],
    answer: 0,
    explanation: "Arrays use square brackets [].",
  },
  {
    id: 93,
    topic: "JavaScript",
    question: "Which method adds an item to the end of an array?",
    options: ["push()", "pop()", "shift()", "unshift()"],
    answer: 0,
    explanation: "push adds to end; pop removes from end.",
  },
  {
    id: 94,
    topic: "JavaScript",
    question: "Which method removes an item from the end of an array?",
    options: ["pop()", "push()", "shift()", "join()"],
    answer: 0,
    explanation: "pop removes last element.",
  },
  {
    id: 95,
    topic: "JavaScript",
    question: "Which DOM method selects an element by id?",
    options: ["document.getElementById()", "document.getElementsByClassName()", "document.querySelectorAll()", "document.getElementsByTagName()"],
    answer: 0,
    explanation: "getElementById returns element with matching id.",
  },
  {
    id: 96,
    topic: "JavaScript",
    question: "Which property sets/gets the value of an input element?",
    options: ["value", "innerHTML", "textContent", "style"],
    answer: 0,
    explanation: "input.value reads/writes the field value.",
  },
  {
    id: 97,
    topic: "JavaScript",
    question: "Which property changes HTML inside an element?",
    options: ["innerHTML", "value", "href", "src"],
    answer: 0,
    explanation: "innerHTML sets the HTML content (use carefully).",
  },
  {
    id: 98,
    topic: "JavaScript",
    question: "Which is the correct way to add a click event listener?",
    options: [
      "btn.addEventListener('click', handler)",
      "btn.onClick(handler)",
      "btn.addClick(handler)",
      "btn.listen('click', handler)",
    ],
    answer: 0,
    explanation: "addEventListener is the standard DOM API.",
  },
  {
    id: 99,
    topic: "JavaScript",
    question: "Which API stores key/value data in the browser?",
    options: ["localStorage", "sessionSQL", "cookieJar()", "browserDB()"],
    answer: 0,
    explanation: "localStorage stores persistent key/value strings.",
  },
  {
    id: 100,
    topic: "JavaScript",
    question: "Which structure is used for error handling in JavaScript?",
    options: ["try...catch", "if...else", "for...of", "switch...case"],
    answer: 0,
    explanation: "try/catch handles runtime errors safely.",
  },
  
  // ===== JavaScript (101 - 160) =====
  {
    id: 101,
    topic: "JavaScript",
    question: "Which method selects an element by its id?",
    options: ["document.getElementById", "document.getElementsByClassName", "document.querySelectorAll", "window.getId"],
    answer: 0,
    explanation: "getElementById returns the element with the matching id.",
  },
  {
    id: 102,
    topic: "JavaScript",
    question: "Which property changes the HTML content inside an element?",
    options: ["innerHTML", "textValue", "valueHTML", "contentText"],
    answer: 0,
    explanation: "innerHTML sets (or gets) HTML inside an element.",
  },
  {
    id: 103,
    topic: "JavaScript",
    question: "How do you read text typed into an <input> element?",
    options: ["input.innerHTML", "input.value", "input.text", "input.content"],
    answer: 1,
    explanation: "Input elements store user text in the value property.",
  },
  {
    id: 104,
    topic: "JavaScript",
    question: "Which method attaches an event handler to an element?",
    options: ["addEventListener", "addEvent", "listen", "onEvent"],
    answer: 0,
    explanation: "addEventListener('click', fn) is the standard way.",
  },
  {
    id: 105,
    topic: "JavaScript",
    question: "Which keyword creates a block-scoped variable?",
    options: ["let", "var", "static", "define"],
    answer: 0,
    explanation: "let is block-scoped; var is function-scoped.",
  },
  {
    id: 106,
    topic: "JavaScript",
    question: "Which keyword creates a constant (cannot be reassigned)?",
    options: ["const", "let", "var", "final"],
    answer: 0,
    explanation: "const prevents reassignment (but objects can still be mutated).",
  },
  {
    id: 107,
    topic: "JavaScript",
    question: "Which operator compares both value and type?",
    options: ["===", "==", "=", "!="],
    answer: 0,
    explanation: "=== checks strict equality (value + type).",
  },
  {
    id: 108,
    topic: "JavaScript",
    question: "Which is the correct single-line comment syntax?",
    options: ["// comment", "/* comment */", "<!-- comment -->", "# comment"],
    answer: 0,
    explanation: "// is a single-line JavaScript comment.",
  },
  {
    id: 109,
    topic: "JavaScript",
    question: "Which loop is best when you know the exact number of repetitions?",
    options: ["for", "while", "do...while", "switch"],
    answer: 0,
    explanation: "for is commonly used when you know the count.",
  },
  {
    id: 110,
    topic: "JavaScript",
    question: "Which statement is used to handle runtime errors safely?",
    options: ["try...catch", "if...else", "for...of", "switch"],
    answer: 0,
    explanation: "try/catch handles exceptions thrown at runtime.",
  },

  {
    id: 111,
    topic: "JavaScript",
    question: "Which method runs a function once after a delay?",
    options: ["setTimeout", "setInterval", "delay", "wait"],
    answer: 0,
    explanation: "setTimeout(fn, ms) runs once after ms.",
  },
  {
    id: 112,
    topic: "JavaScript",
    question: "Which method runs a function repeatedly every interval?",
    options: ["setInterval", "setTimeout", "repeat", "loopInterval"],
    answer: 0,
    explanation: "setInterval(fn, ms) repeats until cleared.",
  },
  {
    id: 113,
    topic: "JavaScript",
    question: "Which method stops a setInterval timer?",
    options: ["clearInterval", "stopInterval", "endInterval", "cancelTimeout"],
    answer: 0,
    explanation: "clearInterval(id) cancels repeating timers.",
  },
  {
    id: 114,
    topic: "JavaScript",
    question: "Which method selects the first element matching a CSS selector?",
    options: ["document.querySelector", "document.querySelectorAll", "document.getElementsByName", "document.getBySelector"],
    answer: 0,
    explanation: "querySelector returns the first match.",
  },
  {
    id: 115,
    topic: "JavaScript",
    question: "Which method selects ALL elements matching a CSS selector?",
    options: ["document.querySelectorAll", "document.querySelector", "document.getElementById", "document.selectAll"],
    answer: 0,
    explanation: "querySelectorAll returns a NodeList of matches.",
  },
  {
    id: 116,
    topic: "JavaScript",
    question: "Which is a correct arrow function syntax?",
    options: ["() => {}", "function => () {}", "=> function() {}", "arrow() -> {}"],
    answer: 0,
    explanation: "Arrow functions look like: () => { ... }",
  },
  {
    id: 117,
    topic: "JavaScript",
    question: "Which keyword is used to throw a custom error?",
    options: ["throw", "catch", "error", "stop"],
    answer: 0,
    explanation: "throw creates or re-throws an error.",
  },
  {
    id: 118,
    topic: "JavaScript",
    question: "What does JSON.parse() do?",
    options: ["Converts JSON string to object", "Converts object to JSON string", "Encrypts text", "Deletes properties"],
    answer: 0,
    explanation: "JSON.parse turns JSON text into an object.",
  },
  {
    id: 119,
    topic: "JavaScript",
    question: "What does JSON.stringify() do?",
    options: ["Converts object to JSON string", "Converts JSON string to object", "Validates HTML", "Minifies CSS"],
    answer: 0,
    explanation: "JSON.stringify turns an object into JSON text.",
  },
  {
    id: 120,
    topic: "JavaScript",
    question: "Which storage keeps data even after browser refresh/reopen (usually)?",
    options: ["localStorage", "let variables", "function scope", "DOM nodes"],
    answer: 0,
    explanation: "localStorage persists as key-value strings in the browser.",
  },

  // DOM + HTML Integration
  {
    id: 121,
    topic: "JavaScript",
    question: "Which property is commonly used to change CSS from JavaScript?",
    options: ["element.style", "element.css", "element.design", "element.format"],
    answer: 0,
    explanation: "element.style.property = 'value' changes inline styles.",
  },
  {
    id: 122,
    topic: "JavaScript",
    question: "Which event runs when a button is clicked?",
    options: ["click", "submit", "load", "change"],
    answer: 0,
    explanation: "click fires when an element is clicked.",
  },
  {
    id: 123,
    topic: "JavaScript",
    question: "Which event runs when an input value changes (after leaving the input)?",
    options: ["change", "click", "load", "resize"],
    answer: 0,
    explanation: "change often fires when focus leaves and value changed.",
  },
  {
    id: 124,
    topic: "JavaScript",
    question: "Which event runs as you type in an input (real-time)?",
    options: ["input", "change", "submit", "scroll"],
    answer: 0,
    explanation: "input fires on every value change while typing.",
  },
  {
    id: 125,
    topic: "JavaScript",
    question: "Which method prevents a form from submitting (page reload)?",
    options: ["event.preventDefault()", "event.stop()", "form.cancel()", "stopSubmit()"],
    answer: 0,
    explanation: "preventDefault stops the default submit behavior.",
  },
  {
    id: 126,
    topic: "JavaScript",
    question: "Which is the correct way to set text content (no HTML) safely?",
    options: ["textContent", "innerHTML", "valueHTML", "writeHTML"],
    answer: 0,
    explanation: "textContent avoids interpreting HTML (safer).",
  },
  {
    id: 127,
    topic: "JavaScript",
    question: "Which is true about innerHTML?",
    options: ["It can insert HTML tags", "It only inserts plain text", "It changes CSS only", "It cannot be read"],
    answer: 0,
    explanation: "innerHTML inserts HTML and can be unsafe if not sanitized.",
  },
  {
    id: 128,
    topic: "JavaScript",
    question: "Which is the correct way to get an element’s attribute value?",
    options: ["element.getAttribute('href')", "element.getAttr('href')", "element.readAttribute('href')", "element.attribute('href')"],
    answer: 0,
    explanation: "getAttribute reads an attribute string value.",
  },
  {
    id: 129,
    topic: "JavaScript",
    question: "Which method adds a class to an element?",
    options: ["element.classList.add()", "element.addClass()", "element.class.add()", "element.style.classAdd()"],
    answer: 0,
    explanation: "classList.add('name') adds a CSS class.",
  },
  {
    id: 130,
    topic: "JavaScript",
    question: "Which method removes a class from an element?",
    options: ["element.classList.remove()", "element.removeClass()", "element.class.remove()", "element.style.removeClass()"],
    answer: 0,
    explanation: "classList.remove('name') removes a class.",
  },

  // Functions + loops
  {
    id: 131,
    topic: "JavaScript",
    question: "Which is the correct way to define a function?",
    options: ["function add(a,b){return a+b;}", "def add(a,b): return a+b", "fun add(a,b)=>a+b", "make add(a,b)=a+b"],
    answer: 0,
    explanation: "JavaScript function uses the function keyword (or arrow).",
  },
  {
    id: 132,
    topic: "JavaScript",
    question: "Which is a correct function call?",
    options: ["add(1, 2)", "add = (1, 2)", "call add 1 2", "run(add,1,2,)"],
    answer: 0,
    explanation: "Use parentheses to call functions.",
  },
  {
    id: 133,
    topic: "JavaScript",
    question: "Which loop iterates over array values directly?",
    options: ["for...of", "for...in", "switch", "if"],
    answer: 0,
    explanation: "for...of iterates over values.",
  },
  {
    id: 134,
    topic: "JavaScript",
    question: "Which loop iterates over object keys (property names)?",
    options: ["for...in", "for...of", "while...of", "foreach...in"],
    answer: 0,
    explanation: "for...in loops over keys.",
  },
  {
    id: 135,
    topic: "JavaScript",
    question: "Which statement stops a loop early?",
    options: ["break", "stop", "exit", "end"],
    answer: 0,
    explanation: "break exits the current loop.",
  },
  {
    id: 136,
    topic: "JavaScript",
    question: "Which statement skips to the next loop iteration?",
    options: ["continue", "skip", "next", "pass"],
    answer: 0,
    explanation: "continue jumps to the next iteration.",
  },
  {
    id: 137,
    topic: "JavaScript",
    question: "Which method loops over an array and creates a new array?",
    options: ["map()", "forEach()", "push()", "join()"],
    answer: 0,
    explanation: "map returns a new transformed array.",
  },
  {
    id: 138,
    topic: "JavaScript",
    question: "Which method loops over an array but returns nothing (undefined)?",
    options: ["forEach()", "map()", "filter()", "reduce()"],
    answer: 0,
    explanation: "forEach is for side effects; it returns undefined.",
  },
  {
    id: 139,
    topic: "JavaScript",
    question: "Which method filters array items by a condition?",
    options: ["filter()", "map()", "slice()", "concat()"],
    answer: 0,
    explanation: "filter returns items that match a condition.",
  },
  {
    id: 140,
    topic: "JavaScript",
    question: "Which method reduces an array to one value?",
    options: ["reduce()", "map()", "filter()", "split()"],
    answer: 0,
    explanation: "reduce combines items into one result.",
  },

  // ===== HTML (161 - 200) =====
  {
    id: 161,
    topic: "HTML",
    question: "Which tag creates a hyperlink?",
    options: ["<a>", "<link>", "<p>", "<img>"],
    answer: 0,
    explanation: "<a href='...'> creates a clickable link.",
  },
  {
    id: 162,
    topic: "HTML",
    question: "Which attribute is used to specify a link destination?",
    options: ["href", "src", "alt", "value"],
    answer: 0,
    explanation: "href is the URL of the link.",
  },
  {
    id: 163,
    topic: "HTML",
    question: "Which tag is used to insert an image?",
    options: ["<img>", "<image>", "<picturebox>", "<src>"],
    answer: 0,
    explanation: "<img src='...'> inserts an image.",
  },
  {
    id: 164,
    topic: "HTML",
    question: "Which attribute provides alternative text for an image (accessibility)?",
    options: ["alt", "title", "href", "name"],
    answer: 0,
    explanation: "alt is read by screen readers and helps SEO.",
  },
  {
    id: 165,
    topic: "HTML",
    question: "Which tag creates a table?",
    options: ["<table>", "<tab>", "<tr>", "<td>"],
    answer: 0,
    explanation: "<table> defines a table container.",
  },
  {
    id: 166,
    topic: "HTML",
    question: "Which tag defines a table row?",
    options: ["<tr>", "<td>", "<th>", "<row>"],
    answer: 0,
    explanation: "<tr> is a table row.",
  },
  {
    id: 167,
    topic: "HTML",
    question: "Which tag defines a data cell in a table?",
    options: ["<td>", "<tr>", "<th>", "<cell>"],
    answer: 0,
    explanation: "<td> is a normal cell (data).",
  },
  {
    id: 168,
    topic: "HTML",
    question: "Which tag defines a header cell in a table?",
    options: ["<th>", "<td>", "<tr>", "<head>"],
    answer: 0,
    explanation: "<th> is a header cell (often bold/centered).",
  },
  {
    id: 169,
    topic: "HTML",
    question: "Which tag is used to create a form?",
    options: ["<form>", "<input>", "<button>", "<fieldset>"],
    answer: 0,
    explanation: "<form> groups controls and can submit data.",
  },
  {
    id: 170,
    topic: "HTML",
    question: "Which attribute decides where the form sends data?",
    options: ["action", "method", "name", "for"],
    answer: 0,
    explanation: "action sets the URL where data is submitted.",
  },
  {
    id: 171,
    topic: "HTML",
    question: "Which attribute decides how the form sends data?",
    options: ["method", "action", "id", "class"],
    answer: 0,
    explanation: "method is usually GET or POST.",
  },
  {
    id: 172,
    topic: "HTML",
    question: "Which input type hides typed characters?",
    options: ["password", "text", "email", "hidden"],
    answer: 0,
    explanation: "password masks characters for privacy.",
  },
  {
    id: 173,
    topic: "HTML",
    question: "Which input type provides basic email validation?",
    options: ["email", "text", "mailbox", "address"],
    answer: 0,
    explanation: "type='email' enables browser validation.",
  },
  {
    id: 174,
    topic: "HTML",
    question: "Which tag creates an unordered list?",
    options: ["<ul>", "<ol>", "<li>", "<list>"],
    answer: 0,
    explanation: "<ul> is unordered list (bullets).",
  },
  {
    id: 175,
    topic: "HTML",
    question: "Which tag creates an ordered list?",
    options: ["<ol>", "<ul>", "<li>", "<order>"],
    answer: 0,
    explanation: "<ol> is ordered list (numbers).",
  },
  {
    id: 176,
    topic: "HTML",
    question: "Which tag is used for each list item?",
    options: ["<li>", "<ul>", "<ol>", "<item>"],
    answer: 0,
    explanation: "<li> represents one item in a list.",
  },
  {
    id: 177,
    topic: "HTML",
    question: "Which semantic tag is best for navigation links?",
    options: ["<nav>", "<div>", "<section>", "<aside>"],
    answer: 0,
    explanation: "<nav> is for navigation blocks.",
  },
  {
    id: 178,
    topic: "HTML",
    question: "Which semantic tag is best for the main content area?",
    options: ["<main>", "<header>", "<footer>", "<aside>"],
    answer: 0,
    explanation: "<main> should wrap the page’s main content.",
  },
  {
    id: 179,
    topic: "HTML",
    question: "Which semantic tag is best for footer information?",
    options: ["<footer>", "<bottom>", "<end>", "<section>"],
    answer: 0,
    explanation: "<footer> holds footer content.",
  },
  {
    id: 180,
    topic: "HTML",
    question: "Which is the correct HTML comment syntax?",
    options: ["<!-- comment -->", "// comment", "/* comment */", "# comment"],
    answer: 0,
    explanation: "HTML uses <!-- --> for comments.",
  },

  // CSS basics to finish 200 nicely
  {
    id: 181,
    topic: "CSS",
    question: "Which property changes the text color?",
    options: ["color", "background-color", "font-family", "border-color"],
    answer: 0,
    explanation: "color sets the text color.",
  },
  {
    id: 182,
    topic: "CSS",
    question: "Which property changes the background color?",
    options: ["background-color", "color", "opacity", "display"],
    answer: 0,
    explanation: "background-color sets background color.",
  },
  {
    id: 183,
    topic: "CSS",
    question: "Which selector targets elements by class?",
    options: [".menu", "#menu", "menu()", "@menu"],
    answer: 0,
    explanation: ".class selects elements with that class.",
  },
  {
    id: 184,
    topic: "CSS",
    question: "Which selector targets an element by id?",
    options: ["#header", ".header", "header()", "@header"],
    answer: 0,
    explanation: "#id selects the element with that id.",
  },
  {
    id: 185,
    topic: "CSS",
    question: "Which property adds space inside the border?",
    options: ["padding", "margin", "gap", "space"],
    answer: 0,
    explanation: "padding is inside the border.",
  },
  {
    id: 186,
    topic: "CSS",
    question: "Which property adds space outside the border?",
    options: ["margin", "padding", "outline", "spacing"],
    answer: 0,
    explanation: "margin is outside the border.",
  },
  {
    id: 187,
    topic: "CSS",
    question: "Which property rounds corners?",
    options: ["border-radius", "corner", "radius", "round-border"],
    answer: 0,
    explanation: "border-radius rounds element corners.",
  },
  {
    id: 188,
    topic: "CSS",
    question: "Which property makes an element invisible but keeps its space?",
    options: ["visibility: hidden", "display: none", "opacity: 0", "position: fixed"],
    answer: 0,
    explanation: "visibility:hidden keeps layout space.",
  },
  {
    id: 189,
    topic: "CSS",
    question: "Which property removes an element from layout completely?",
    options: ["display: none", "visibility: hidden", "opacity: 0", "z-index: -1"],
    answer: 0,
    explanation: "display:none removes it from the document flow.",
  },
  {
    id: 190,
    topic: "CSS",
    question: "Which position stays on the screen when scrolling?",
    options: ["fixed", "relative", "absolute", "static"],
    answer: 0,
    explanation: "fixed positions relative to the viewport.",
  },
  {
    id: 191,
    topic: "CSS",
    question: "Which position moves relative to its original position?",
    options: ["relative", "absolute", "fixed", "inherit"],
    answer: 0,
    explanation: "relative shifts element but keeps its original space.",
  },
  {
    id: 192,
    topic: "CSS",
    question: "Which property sets an element’s width?",
    options: ["width", "size-x", "element-width", "block-width"],
    answer: 0,
    explanation: "width controls element width.",
  },
  {
    id: 193,
    topic: "CSS",
    question: "Which property sets an element’s height?",
    options: ["height", "size-y", "element-height", "block-height"],
    answer: 0,
    explanation: "height controls element height.",
  },
  {
    id: 194,
    topic: "CSS",
    question: "Which CSS feature is used for responsive design rules by screen size?",
    options: ["media queries", "variables", "keyframes", "imports"],
    answer: 0,
    explanation: "Media queries apply styles based on device size/orientation.",
  },
  {
    id: 195,
    topic: "CSS",
    question: "Which media query targets screens up to 600px width?",
    options: ["@media (max-width: 600px)", "@media (min-width: 600px)", "@media (width: 600px)", "@media (device: 600px)"],
    answer: 0,
    explanation: "max-width targets small screens.",
  },
  {
    id: 196,
    topic: "CSS",
    question: "Which property changes the font?",
    options: ["font-family", "font-size", "font-weight", "text-align"],
    answer: 0,
    explanation: "font-family sets the font name.",
  },
  {
    id: 197,
    topic: "CSS",
    question: "Which property changes font size?",
    options: ["font-size", "text-size", "size", "font-scale"],
    answer: 0,
    explanation: "font-size sets text size.",
  },
  {
    id: 198,
    topic: "CSS",
    question: "Which property makes text bold?",
    options: ["font-weight", "font-style", "text-bold", "weight"],
    answer: 0,
    explanation: "font-weight: bold makes text bold.",
  },
  {
    id: 199,
    topic: "CSS",
    question: "Which property centers inline text inside a block?",
    options: ["text-align: center", "align: center", "justify: center", "center-text: true"],
    answer: 0,
    explanation: "text-align centers inline content like text.",
  },
  {
    id: 200,
    topic: "CSS",
    question: "Which statement best describes the CSS box model?",
    options: ["content + padding + border + margin", "only margin", "only padding", "only border"],
    answer: 0,
    explanation: "The box model includes content, padding, border, and margin.",
  },


  
];
