// questions.js
const QUESTION_BANK = [
  // =========================
  // HTML (1 - 34)
  // =========================
  {
    id: 1,
    topic: "HTML",
    question: "What is a webpage?",
    options: [
      "A single document displayed in a browser",
      "A group of servers connected to the internet",
      "A programming language for styling",
      "A database table for users",
    ],
    answer: 0,
    explanation: "A webpage is one page/document viewed in a browser.",
  },
  {
    id: 2,
    topic: "HTML",
    question: "What is a website?",
    options: [
      "A collection of related webpages under one domain",
      "A single HTML tag",
      "A web browser extension",
      "A server operating system",
    ],
    answer: 0,
    explanation: "A website is multiple pages linked together.",
  },
  {
    id: 3,
    topic: "HTML",
    question: "Which tool is used to view webpages?",
    options: ["Web browser", "Text editor", "Compiler", "Database"],
    answer: 0,
    explanation: "Browsers render HTML/CSS/JS into visible pages.",
  },
  {
    id: 4,
    topic: "HTML",
    question: "Which is a text editor commonly used for web development?",
    options: ["VS Code", "Chrome", "MySQL", "Apache"],
    answer: 0,
    explanation: "VS Code is a text editor for writing code.",
  },
  {
    id: 5,
    topic: "HTML",
    question: "What does URL stand for?",
    options: [
      "Uniform Resource Locator",
      "Universal Render Language",
      "User Reference Link",
      "Unified Routing Level",
    ],
    answer: 0,
    explanation: "URL = Uniform Resource Locator.",
  },
  {
    id: 6,
    topic: "HTML",
    question: "What is a hyperlink used for?",
    options: [
      "To connect one page/resource to another",
      "To change background color",
      "To store data in the browser",
      "To create a database relationship",
    ],
    answer: 0,
    explanation: "Links navigate to another page, section, or resource.",
  },
  {
    id: 7,
    topic: "HTML",
    question: "Which file extension is correct for an HTML file?",
    options: [".html", ".css", ".js", ".php"],
    answer: 0,
    explanation: "HTML files typically end with .html",
  },
  {
    id: 8,
    topic: "HTML",
    question: "Which tag defines the main structure of an HTML document?",
    options: ["<!DOCTYPE html>", "<meta>", "<link>", "<script>"],
    answer: 0,
    explanation: "DOCTYPE tells the browser to use HTML5 standards mode.",
  },
  {
    id: 9,
    topic: "HTML",
    question: "Which tag contains metadata like charset and title links?",
    options: ["<head>", "<body>", "<footer>", "<section>"],
    answer: 0,
    explanation: "<head> contains metadata and resource links.",
  },
  {
    id: 10,
    topic: "HTML",
    question: "Which tag displays visible content on the page?",
    options: ["<body>", "<head>", "<title>", "<meta>"],
    answer: 0,
    explanation: "Visible elements are inside <body>.",
  },
  {
    id: 11,
    topic: "HTML",
    question: "Which is a correct heading tag order (largest to smallest)?",
    options: ["<h1> to <h6>", "<h6> to <h1>", "<p> to <h1>", "<title> to <h6>"],
    answer: 0,
    explanation: "Heading levels go from h1 (largest) to h6 (smallest).",
  },
  {
    id: 12,
    topic: "HTML",
    question: "Which tag is used for a paragraph?",
    options: ["<p>", "<h1>", "<div>", "<span>"],
    answer: 0,
    explanation: "<p> is for paragraphs.",
  },
  {
    id: 13,
    topic: "HTML",
    question: "Which tag creates a line break?",
    options: ["<br>", "<hr>", "<p>", "<li>"],
    answer: 0,
    explanation: "<br> inserts a line break.",
  },
  {
    id: 14,
    topic: "HTML",
    question: "Which tag creates a horizontal line separator?",
    options: ["<hr>", "<br>", "<span>", "<div>"],
    answer: 0,
    explanation: "<hr> is a thematic break line.",
  },
  {
    id: 15,
    topic: "HTML",
    question: "Which tag is used for an unordered list?",
    options: ["<ul>", "<ol>", "<li>", "<list>"],
    answer: 0,
    explanation: "<ul> is unordered list; <li> is list item.",
  },
  {
    id: 16,
    topic: "HTML",
    question: "Which tag is used for an ordered list?",
    options: ["<ol>", "<ul>", "<li>", "<order>"],
    answer: 0,
    explanation: "<ol> creates a numbered list.",
  },
  {
    id: 17,
    topic: "HTML",
    question: "Which tag defines a list item?",
    options: ["<li>", "<ul>", "<ol>", "<item>"],
    answer: 0,
    explanation: "<li> is used inside ul/ol.",
  },
  {
    id: 18,
    topic: "HTML",
    question: "Which tag is used to display an image?",
    options: ["<img>", "<image>", "<picture>", "<src>"],
    answer: 0,
    explanation: "<img> displays an image using src attribute.",
  },
  {
    id: 19,
    topic: "HTML",
    question: "Which attribute is required to specify the image file location?",
    options: ["src", "alt", "href", "type"],
    answer: 0,
    explanation: "src points to the image resource.",
  },
  {
    id: 20,
    topic: "HTML",
    question: "Which attribute helps SEO/accessibility for images?",
    options: ["alt", "src", "width", "class"],
    answer: 0,
    explanation: "alt provides text alternative for screen readers and SEO.",
  },
  {
    id: 21,
    topic: "HTML",
    question: "Which tag creates a link to another page?",
    options: ["<a>", "<link>", "<href>", "<nav>"],
    answer: 0,
    explanation: "<a href='...'> is hyperlink.",
  },
  {
    id: 22,
    topic: "HTML",
    question: "Which attribute defines the destination of an <a> tag?",
    options: ["href", "src", "target", "rel"],
    answer: 0,
    explanation: "href is the URL destination.",
  },
  {
    id: 23,
    topic: "HTML",
    question: "Which value opens a link in a new tab?",
    options: ['target="_blank"', 'target="_self"', 'rel="nofollow"', 'href="_blank"'],
    answer: 0,
    explanation: "target='_blank' opens a new tab/window.",
  },
  {
    id: 24,
    topic: "HTML",
    question: "Which tag is used to group content as a block container?",
    options: ["<div>", "<span>", "<em>", "<strong>"],
    answer: 0,
    explanation: "<div> is a block-level grouping container.",
  },
  {
    id: 25,
    topic: "HTML",
    question: "Which tag is used to group inline text?",
    options: ["<span>", "<div>", "<section>", "<article>"],
    answer: 0,
    explanation: "<span> is an inline container.",
  },
  {
    id: 26,
    topic: "HTML",
    question: "Which semantic tag is best for site navigation?",
    options: ["<nav>", "<div>", "<span>", "<table>"],
    answer: 0,
    explanation: "<nav> indicates navigation links section.",
  },
  {
    id: 27,
    topic: "HTML",
    question: "Which semantic tag is best for main content of the page?",
    options: ["<main>", "<aside>", "<footer>", "<header>"],
    answer: 0,
    explanation: "<main> holds the primary content.",
  },
  {
    id: 28,
    topic: "HTML",
    question: "Which tag is used for a table row?",
    options: ["<tr>", "<td>", "<th>", "<table>"],
    answer: 0,
    explanation: "<tr> is a table row.",
  },
  {
    id: 29,
    topic: "HTML",
    question: "Which tag is used for table header cell?",
    options: ["<th>", "<td>", "<tr>", "<thead>"],
    answer: 0,
    explanation: "<th> is a header cell (bold by default).",
  },
  {
    id: 30,
    topic: "HTML",
    question: "Which tag is used for table data cell?",
    options: ["<td>", "<th>", "<tr>", "<tbody>"],
    answer: 0,
    explanation: "<td> holds regular table data.",
  },
  {
    id: 31,
    topic: "HTML",
    question: "Which element is used to collect user input text?",
    options: ["<input>", "<form>", "<label>", "<fieldset>"],
    answer: 0,
    explanation: "<input> creates an input field.",
  },
  {
    id: 32,
    topic: "HTML",
    question: "Which attribute is important for sending form data (input key name)?",
    options: ["name", "id", "class", "style"],
    answer: 0,
    explanation: "name is the key used in submitted form data.",
  },
  {
    id: 33,
    topic: "HTML",
    question: "Which tag is used to write a comment in HTML?",
    options: ["<!-- comment -->", "// comment", "/* comment */", "# comment"],
    answer: 0,
    explanation: "HTML comments use <!-- -->.",
  },
  {
    id: 34,
    topic: "HTML",
    question: "Which tag is best for SEO page title shown in the browser tab?",
    options: ["<title>", "<h1>", "<meta>", "<header>"],
    answer: 0,
    explanation: "<title> sets the page title in the tab/search results.",
  },

  // =========================
  // CSS (35 - 67)
  // =========================
  {
    id: 35,
    topic: "CSS",
    question: "What is CSS mainly used for?",
    options: [
      "Styling and layout of webpages",
      "Storing data in database",
      "Creating server routes",
      "Compiling JavaScript",
    ],
    answer: 0,
    explanation: "CSS controls design and layout.",
  },
  {
    id: 36,
    topic: "CSS",
    question: "Which is a correct CSS syntax?",
    options: [
      "selector { property: value; }",
      "selector ( property = value )",
      "{ selector: property=value }",
      "property: value -> selector",
    ],
    answer: 0,
    explanation: "CSS uses selector { property: value; }",
  },
  {
    id: 37,
    topic: "CSS",
    question: "In CSS, what is a selector?",
    options: [
      "The part that chooses which HTML elements to style",
      "The part that sets the property value",
      "A JavaScript function name",
      "A database query",
    ],
    answer: 0,
    explanation: "Selector targets elements like p, .class, #id.",
  },
  {
    id: 38,
    topic: "CSS",
    question: "In CSS, what is a declaration?",
    options: [
      "property: value;",
      "A HTML comment",
      "A file extension",
      "A URL address",
    ],
    answer: 0,
    explanation: "Declarations are property-value pairs.",
  },
  {
    id: 39,
    topic: "CSS",
    question: "Which is inline CSS?",
    options: [
      '<p style="color:red;">Hi</p>',
      "<style>p{color:red;}</style>",
      '<link rel="stylesheet" href="style.css">',
      '@import "style.css";',
    ],
    answer: 0,
    explanation: "Inline CSS is in the style attribute.",
  },
  {
    id: 40,
    topic: "CSS",
    question: "Which is internal CSS?",
    options: [
      "<style>p{color:red;}</style>",
      '<p style="color:red;">Hi</p>',
      '<link rel="stylesheet" href="style.css">',
      "p:color=red",
    ],
    answer: 0,
    explanation: "Internal CSS is inside <style> in the HTML file.",
  },
  {
    id: 41,
    topic: "CSS",
    question: "Which is external CSS?",
    options: [
      '<link rel="stylesheet" href="style.css">',
      '<p style="color:red;">Hi</p>',
      "<style>p{color:red;}</style>",
      "<script src='style.css'></script>",
    ],
    answer: 0,
    explanation: "External CSS uses <link> to load a .css file.",
  },
  {
    id: 42,
    topic: "CSS",
    question: "Which CSS property changes text color?",
    options: ["color", "background-color", "font-style", "display"],
    answer: 0,
    explanation: "color controls the text color.",
  },
  {
    id: 43,
    topic: "CSS",
    question: "Which property changes the background color?",
    options: ["background-color", "color", "opacity", "border-color"],
    answer: 0,
    explanation: "background-color sets background.",
  },
  {
    id: 44,
    topic: "CSS",
    question: "Which property controls transparency?",
    options: ["opacity", "visibility", "display", "z-index"],
    answer: 0,
    explanation: "opacity ranges 0 to 1.",
  },
  {
    id: 45,
    topic: "CSS",
    question: "Which property sets a background image?",
    options: ["background-image", "image-src", "bg-src", "background-photo"],
    answer: 0,
    explanation: "background-image: url(...);",
  },
  {
    id: 46,
    topic: "CSS",
    question: "Which display value hides an element but keeps its space?",
    options: ["visibility: hidden", "display: none", "opacity: 0", "position: fixed"],
    answer: 0,
    explanation: "visibility:hidden keeps layout space; display:none removes it.",
  },
  {
    id: 47,
    topic: "CSS",
    question: "Which display value removes an element from layout completely?",
    options: ["display: none", "visibility: hidden", "opacity: 0", "position: relative"],
    answer: 0,
    explanation: "display:none removes from layout flow.",
  },
  {
    id: 48,
    topic: "CSS",
    question: "Which position type places element relative to its normal position?",
    options: ["relative", "absolute", "fixed", "sticky"],
    answer: 0,
    explanation: "position:relative offsets from normal position.",
  },
  {
    id: 49,
    topic: "CSS",
    question: "Which position type places element relative to nearest positioned ancestor?",
    options: ["absolute", "relative", "fixed", "static"],
    answer: 0,
    explanation: "absolute uses nearest ancestor with position set (not static).",
  },
  {
    id: 50,
    topic: "CSS",
    question: "Which position type stays in the same place on screen during scroll?",
    options: ["fixed", "absolute", "relative", "static"],
    answer: 0,
    explanation: "fixed attaches to viewport.",
  },
  {
    id: 51,
    topic: "CSS",
    question: "Which position type behaves like relative until it reaches a scroll point?",
    options: ["sticky", "fixed", "absolute", "static"],
    answer: 0,
    explanation: "sticky sticks after crossing a threshold like top: 0.",
  },
  {
    id: 52,
    topic: "CSS",
    question: "Which property sets element width?",
    options: ["width", "size", "length", "box-width"],
    answer: 0,
    explanation: "width sets the element width.",
  },
  {
    id: 53,
    topic: "CSS",
    question: "Which property sets element height?",
    options: ["height", "size", "length", "box-height"],
    answer: 0,
    explanation: "height sets the element height.",
  },
  {
    id: 54,
    topic: "CSS",
    question: "Which property creates space inside the border?",
    options: ["padding", "margin", "gap", "outline"],
    answer: 0,
    explanation: "Padding is inside, margin is outside.",
  },
  {
    id: 55,
    topic: "CSS",
    question: "Which property creates space outside the border?",
    options: ["margin", "padding", "gap", "outline"],
    answer: 0,
    explanation: "Margin is outside the element border.",
  },
  {
    id: 56,
    topic: "CSS",
    question: "Which property rounds the corners of an element?",
    options: ["border-radius", "border-style", "corner-radius", "radius"],
    answer: 0,
    explanation: "border-radius rounds corners.",
  },
  {
    id: 57,
    topic: "CSS",
    question: "Which property sets the border thickness/style/color?",
    options: ["border", "outline", "stroke", "edge"],
    answer: 0,
    explanation: "border: 1px solid #000; etc.",
  },
  {
    id: 58,
    topic: "CSS",
    question: "Which value centers a block element horizontally (common case)?",
    options: ["margin: 0 auto", "padding: auto", "display: center", "position: center"],
    answer: 0,
    explanation: "margin-left/right auto centers with width set.",
  },
  {
    id: 59,
    topic: "CSS",
    question: "Which property changes font size?",
    options: ["font-size", "text-size", "size", "font-weight"],
    answer: 0,
    explanation: "font-size controls text size.",
  },
  {
    id: 60,
    topic: "CSS",
    question: "Which property changes font weight (boldness)?",
    options: ["font-weight", "font-style", "font-size", "text-decoration"],
    answer: 0,
    explanation: "font-weight: 700; etc.",
  },
  {
    id: 61,
    topic: "CSS",
    question: "Which property aligns text horizontally?",
    options: ["text-align", "align-items", "justify-content", "vertical-align"],
    answer: 0,
    explanation: "text-align affects inline content inside an element.",
  },
  {
    id: 62,
    topic: "CSS",
    question: "Which CSS feature is used for responsive design?",
    options: ["media queries", "variables", "comments", "tags"],
    answer: 0,
    explanation: "@media rules change styles by screen conditions.",
  },
  {
    id: 63,
    topic: "CSS",
    question: "Which media query is best for maximum width 600px?",
    options: [
      "@media (max-width: 600px) { ... }",
      "@media (min-width: 600px) { ... }",
      "@media width <= 600 { ... }",
      "@media screen:600 { ... }",
    ],
    answer: 0,
    explanation: "max-width targets smaller screens up to 600px.",
  },
  {
    id: 64,
    topic: "CSS",
    question: "Which media orientation targets portrait mode?",
    options: [
      "@media (orientation: portrait) { ... }",
      "@media (portrait: true) { ... }",
      "@media (rotate: 0) { ... }",
      "@media (direction: portrait) { ... }",
    ],
    answer: 0,
    explanation: "orientation: portrait is correct syntax.",
  },
  {
    id: 65,
    topic: "CSS",
    question: "Which CSS type imports another CSS file inside a CSS file?",
    options: ["@import", "<link>", "<script>", "require()"],
    answer: 0,
    explanation: "@import url('file.css');",
  },
  {
    id: 66,
    topic: "CSS",
    question: "Which selector targets an element with id='main'?",
    options: ["#main", ".main", "main", "*main"],
    answer: 0,
    explanation: "# targets id.",
  },
  {
    id: 67,
    topic: "CSS",
    question: "Which selector targets elements with class='box'?",
    options: [".box", "#box", "box", "@box"],
    answer: 0,
    explanation: ". targets class.",
  },

  // =========================
  // JavaScript (68 - 100)
  // =========================
  {
    id: 68,
    topic: "JavaScript",
    question: "What is JavaScript mainly used for on a webpage?",
    options: [
      "Adding interaction and logic",
      "Creating table rows",
      "Writing server database schema",
      "Replacing CSS completely",
    ],
    answer: 0,
    explanation: "JS adds behavior (clicks, validation, DOM updates).",
  },
  {
    id: 69,
    topic: "JavaScript",
    question: "Which tag is used to include JavaScript in HTML?",
    options: ["<script>", "<style>", "<link>", "<meta>"],
    answer: 0,
    explanation: "<script> is for JavaScript.",
  },
  {
    id: 70,
    topic: "JavaScript",
    question: "What is the recommended place to load a script for beginners?",
    options: [
      "Before the closing </body> tag",
      "Inside <title>",
      "Inside <meta>",
      "Before <!DOCTYPE html>",
    ],
    answer: 0,
    explanation: "So HTML elements exist before JS runs.",
  },
  {
    id: 71,
    topic: "JavaScript",
    question: "Which keyword creates a variable that can be reassigned?",
    options: ["let", "const", "fixed", "static"],
    answer: 0,
    explanation: "let can be reassigned; const cannot.",
  },
  {
    id: 72,
    topic: "JavaScript",
    question: "Which keyword creates a variable that should not be reassigned?",
    options: ["const", "let", "var", "change"],
    answer: 0,
    explanation: "const prevents reassignment of the variable reference.",
  },
  {
    id: 73,
    topic: "JavaScript",
    question: "Which is a correct JavaScript comment (single line)?",
    options: ["// comment", "<!-- comment -->", "/*/ comment", "# comment"],
    answer: 0,
    explanation: "// starts a single-line comment in JS.",
  },
  {
    id: 74,
    topic: "JavaScript",
    question: "Which is NOT a primitive type in JavaScript?",
    options: ["object", "string", "number", "boolean"],
    answer: 0,
    explanation: "object is reference type; others listed are primitive.",
  },
  {
    id: 75,
    topic: "JavaScript",
    question: "Which function converts a string to a number (common)?",
    options: ["Number()", "String()", "Bool()", "Int()"],
    answer: 0,
    explanation: "Number('20') -> 20.",
  },
  {
    id: 76,
    topic: "JavaScript",
    question: "What is the result of '2' + 2 in JavaScript?",
    options: ["'22'", "4", "'4'", "NaN"],
    answer: 0,
    explanation: "String + number becomes string concatenation.",
  },
  {
    id: 77,
    topic: "JavaScript",
    question: "Which operator checks strict equality (value and type)?",
    options: ["===", "==", "=", "!=="],
    answer: 0,
    explanation: "=== compares value and type.",
  },
  {
    id: 78,
    topic: "JavaScript",
    question: "Which operator means 'not equal (strict)'?",
    options: ["!==", "!=", "===", "="],
    answer: 0,
    explanation: "!== checks strict not equal (type+value).",
  },
  {
    id: 79,
    topic: "JavaScript",
    question: "Which operator is used for logical AND?",
    options: ["&&", "||", "!", "&"],
    answer: 0,
    explanation: "&& requires both conditions to be true.",
  },
  {
    id: 80,
    topic: "JavaScript",
    question: "Which operator is used for logical OR?",
    options: ["||", "&&", "!", "|"],
    answer: 0,
    explanation: "|| true if at least one condition is true.",
  },
  {
    id: 81,
    topic: "JavaScript",
    question: "Which is a correct template literal syntax?",
    options: ["`Hello ${name}`", "'Hello ${name}'", '"Hello ${name}"', "`Hello (name)`"],
    answer: 0,
    explanation: "Template literals use backticks and ${}.",
  },
  {
    id: 82,
    topic: "JavaScript",
    question: "Which method removes whitespace from both ends of a string?",
    options: ["trim()", "slice()", "split()", "join()"],
    answer: 0,
    explanation: "trim() removes leading/trailing spaces.",
  },
  {
    id: 83,
    topic: "JavaScript",
    question: "Which statement is used for multiple conditions (if/else)?",
    options: ["if ... else if ... else", "for ... of", "try ... catch", "switch ... case only"],
    answer: 0,
    explanation: "if/else if/else handles multiple condition branches.",
  },
  {
    id: 84,
    topic: "JavaScript",
    question: "Which statement is best when matching fixed values (menu/options)?",
    options: ["switch", "while", "try", "import"],
    answer: 0,
    explanation: "switch is convenient for fixed cases.",
  },
  {
    id: 85,
    topic: "JavaScript",
    question: "Which loop is commonly used when you know the count?",
    options: ["for", "while", "do...while", "try...catch"],
    answer: 0,
    explanation: "for loop uses init/condition/update.",
  },
  {
    id: 86,
    topic: "JavaScript",
    question: "Which loop is best for iterating values in an array (modern)?",
    options: ["for...of", "for...in", "switch", "if...else"],
    answer: 0,
    explanation: "for...of gives values of iterable (array).",
  },
  {
    id: 87,
    topic: "JavaScript",
    question: "Which loop iterates object keys (or array indexes)?",
    options: ["for...in", "for...of", "for (;;){}", "switch"],
    answer: 0,
    explanation: "for...in iterates enumerable keys.",
  },
  {
    id: 88,
    topic: "JavaScript",
    question: "Which keyword defines a function (classic syntax)?",
    options: ["function", "func", "def", "lambda"],
    answer: 0,
    explanation: "function keyword defines a function in JS.",
  },
  {
    id: 89,
    topic: "JavaScript",
    question: "Which is a correct arrow function?",
    options: ["const add = (a,b) => a + b;", "const add(a,b) -> a+b;", "arrow add = a+b;", "function => add()"],
    answer: 0,
    explanation: "Arrow functions use =>.",
  },
  {
    id: 90,
    topic: "JavaScript",
    question: "What does 'return' do in a function?",
    options: [
      "Sends a value back and stops the function",
      "Repeats the function",
      "Prints to the screen",
      "Declares a new variable",
    ],
    answer: 0,
    explanation: "return ends function and provides output value.",
  },
  {
    id: 91,
    topic: "JavaScript",
    question: "Which creates an object literal?",
    options: ["{ name: 'A' }", "['name','A']", "(name='A')", "<object>A</object>"],
    answer: 0,
    explanation: "Object literal uses { key: value }.",
  },
  {
    id: 92,
    topic: "JavaScript",
    question: "Which creates an array?",
    options: ["[1,2,3]", "{1,2,3}", "(1,2,3)", "<array>1</array>"],
    answer: 0,
    explanation: "Arrays use square brackets [].",
  },
  {
    id: 93,
    topic: "JavaScript",
    question: "Which method adds an item to the end of an array?",
    options: ["push()", "pop()", "shift()", "unshift()"],
    answer: 0,
    explanation: "push adds to end; pop removes from end.",
  },
  {
    id: 94,
    topic: "JavaScript",
    question: "Which method removes an item from the end of an array?",
    options: ["pop()", "push()", "shift()", "join()"],
    answer: 0,
    explanation: "pop removes last element.",
  },
  {
    id: 95,
    topic: "JavaScript",
    question: "Which DOM method selects an element by id?",
    options: ["document.getElementById()", "document.getElementsByClassName()", "document.querySelectorAll()", "document.getElementsByTagName()"],
    answer: 0,
    explanation: "getElementById returns element with matching id.",
  },
  {
    id: 96,
    topic: "JavaScript",
    question: "Which property sets/gets the value of an input element?",
    options: ["value", "innerHTML", "textContent", "style"],
    answer: 0,
    explanation: "input.value reads/writes the field value.",
  },
  {
    id: 97,
    topic: "JavaScript",
    question: "Which property changes HTML inside an element?",
    options: ["innerHTML", "value", "href", "src"],
    answer: 0,
    explanation: "innerHTML sets the HTML content (use carefully).",
  },
  {
    id: 98,
    topic: "JavaScript",
    question: "Which is the correct way to add a click event listener?",
    options: [
      "btn.addEventListener('click', handler)",
      "btn.onClick(handler)",
      "btn.addClick(handler)",
      "btn.listen('click', handler)",
    ],
    answer: 0,
    explanation: "addEventListener is the standard DOM API.",
  },
  {
    id: 99,
    topic: "JavaScript",
    question: "Which API stores key/value data in the browser?",
    options: ["localStorage", "sessionSQL", "cookieJar()", "browserDB()"],
    answer: 0,
    explanation: "localStorage stores persistent key/value strings.",
  },
  {
    id: 100,
    topic: "JavaScript",
    question: "Which structure is used for error handling in JavaScript?",
    options: ["try...catch", "if...else", "for...of", "switch...case"],
    answer: 0,
    explanation: "try/catch handles runtime errors safely.",
  },
];
